// Code generated by goctl. DO NOT EDIT!
// Source: test.proto

package server

import (
	"context"

	"test/internal/logic"
	"test/internal/svc"
	"test/pb/test"
)

type TestServer struct {
	svcCtx *svc.ServiceContext
	test.UnimplementedTestServer
}

func NewTestServer(svcCtx *svc.ServiceContext) *TestServer {
	return &TestServer{
		svcCtx: svcCtx,
	}
}

// 测试接口
func (s *TestServer) Test(ctx context.Context, in *test.TestRequest) (*test.TestResponse, error) {
	l := logic.NewTestLogic(ctx, s.svcCtx)
	return l.Test(in)
}
