// Code generated by goctl. DO NOT EDIT!
// Source: test.proto

package testclient

import (
	"context"

	"test/pb/test"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	TestRequest  = test.TestRequest
	TestResponse = test.TestResponse

	Test interface {
		// 测试接口
		Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error)
	}

	defaultTest struct {
		cli zrpc.Client
	}
)

func NewTest(cli zrpc.Client) Test {
	return &defaultTest{
		cli: cli,
	}
}

// 测试接口
func (m *defaultTest) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestResponse, error) {
	client := test.NewTestClient(m.cli.Conn())
	return client.Test(ctx, in, opts...)
}
